%realistic projection: attenuation and scatter
G=16;
sinoT=zeros(64,64,64,16);
sinoS=zeros(64,64,64,16);
for gate=1:G
    %2 channels: 126-133kev, 133-154kev.
    filename=['c:\simind\ncatdwp' num2str(gate) 's.a02'];
    fid=fopen(filename,'rb');
    bimS=fread(fid,'single');
    fclose(fid);
    bimS=reshape(bimS,[64,64,64]);
    filename=['c:\simind\ncatdwp' num2str(gate) 't.a02'];
    fid=fopen(filename,'rb');
    bimT=fread(fid,'single');
    fclose(fid);
    bimT=reshape(bimT,[64,64,64]);

    filename=['c:\simind\ncatdwp' num2str(gate) 't.a01'];
    fid=fopen(filename,'rb');
    bimLT=fread(fid,'single');
    fclose(fid);
    bimLT=reshape(bimLT,[64,64,64]);
    bimT=bimLT+bimT;
    filename=['c:\simind\ncatdwp' num2str(gate) 's.a01'];
    fid=fopen(filename,'rb');
    bimLS=fread(fid,'single');
    fclose(fid);
    bimLS=reshape(bimLS,[64,64,64]);
    bimS=bimLS+bimS;
    %scale and align for reconstruction
    scal=2.5e5/sum(bimT(:));
    bimT=bimT*scal;
    bimS=bimS*scal;
    for n=1:64
        bimT(:,:,n)=rot90(bimT(:,:,n));
        bimS(:,:,n)=rot90(bimS(:,:,n));
    end
    
    sinoT(:,:,:,gate)=bimT;
    sinoS(:,:,:,gate)=bimS;
end
save ncat_simind_16gsino sinoT sinoS

%NCAT with lesion TEW method (generated by ncat16gles.bat 70% reduction)
G=16;
sinoT=zeros(64,64,64,16);
sinoS=zeros(64,64,64,16);
sinoLT=zeros(64,64,64,16);
for gate=1:G
    %2 channels: 122.5-126kev, 126-154kev.
    filename=['c:\simind\ncatlestew' num2str(gate) 's.a02'];
    fid=fopen(filename,'rb');
    bimS=fread(fid,'single');
    fclose(fid);
    bimS=reshape(bimS,[64,64,64]);%real scatter in peak window
    filename=['c:\simind\ncatlestew' num2str(gate) 't.a02'];
    fid=fopen(filename,'rb');
    bimT=fread(fid,'single');
    fclose(fid);
    bimT=reshape(bimT,[64,64,64]);%total in peak window

    filename=['c:\simind\ncatlestew' num2str(gate) 't.a01'];
    fid=fopen(filename,'rb');
    bimLT=fread(fid,'single');
    fclose(fid);
    bimLT=reshape(bimLT,[64,64,64]);%total in lower window    
    
    %scale and align for reconstruction
    scal=2.5e5*2/sum(bimT(:));%8 million
    bimT=bimT*scal;
    bimS=bimS*scal;
    bimLT=bimLT*scal;
    for n=1:64
        bimT(:,:,n)=rot90(bimT(:,:,n));
        bimS(:,:,n)=rot90(bimS(:,:,n));
        bimLT(:,:,n)=rot90(bimLT(:,:,n));
    end
    
    sinoT(:,:,:,gate)=bimT;
    sinoS(:,:,:,gate)=bimS;
    sinoLT(:,:,:,gate)=bimLT;
end
save ncatles_tew_16gsino sinoT sinoS sinoLT
%noise sinogram
load ncatles_tew_16gsino
sinoP=sinoT-sinoS;
sinoP=random('poiss',sinoP);
sinoS=random('poiss',sinoS);
sinoLT=random('poiss',sinoLT);
save ncatles_tew_16gsino_n1 sinoP sinoS sinoLT